# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ID = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID.setGeometry(QtCore.QRect(50, 40, 21, 16))
        self.ID.setObjectName("ID")
        self.ID_number = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_number.setGeometry(QtCore.QRect(90, 40, 113, 21))
        self.ID_number.setText("")
        self.ID_number.setObjectName("ID_number")
        self.Title_candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title_candidates.setGeometry(QtCore.QRect(100, 70, 91, 16))
        self.Title_candidates.setObjectName("Title_candidates")
        self.Candidate_1 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Candidate_1.setGeometry(QtCore.QRect(90, 90, 100, 20))
        self.Candidate_1.setObjectName("Candidate_1")
        self.Candidate_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Candidate_2.setGeometry(QtCore.QRect(90, 140, 100, 20))
        self.Candidate_2.setObjectName("Candidate_2")
        self.Submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(20, 180, 113, 32))
        self.Submit_button.setObjectName("Submit_button")
        self.Votes_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Votes_button.setGeometry(QtCore.QRect(170, 180, 113, 32))
        self.Votes_button.setObjectName("Votes_button")
        self.Votes_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.Votes_message.setGeometry(QtCore.QRect(60, 220, 181, 71))
        self.Votes_message.setText("")
        self.Votes_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Votes_message.setObjectName("Votes_message")
        self.Error_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error_message.setGeometry(QtCore.QRect(60, 300, 181, 20))
        self.Error_message.setStyleSheet("color: rgb(252, 1, 7);")
        self.Error_message.setText("")
        self.Error_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Error_message.setObjectName("Error_message")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 111, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.ID.setText(_translate("MainWindow", "ID"))
        self.Title_candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.Candidate_1.setText(_translate("MainWindow", "Candidate 1"))
        self.Candidate_2.setText(_translate("MainWindow", "Candidate 2"))
        self.Submit_button.setText(_translate("MainWindow", "Submit Vote"))
        self.Votes_button.setText(_translate("MainWindow", "Total Votes"))
        self.label.setText(_translate("MainWindow", "Voting Application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
